### ISSUE TITLE
build failed  error: ‘FLT_MIN’ was not declared in this scope

### ISSUE THREAD

**Issue by xiazhibin** [facebookincubator/FBX2glTF#228]
I am build on Ubuntu14.04 gcc 5.5.0

I can find `FLT_MIN` declare in `float.h` in `/usr/lib/gcc/x86_64-linux-gnu/5/include`
